# Generated by Django 4.2.7 on 2023-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_videoupload_speedlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='caption',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='videofile',
            field=models.FileField(upload_to='media/%y'),
        ),
    ]
